/**
 * Film-grain overlay, fixed over the entire site at ~4% opacity.
 *
 * This is the cheapest possible fix for the flat, plasticky look that pure
 * CSS colour fields have. The noise is generated by feTurbulence inside a
 * data-URI SVG, so it costs no network request and tiles at any viewport.
 */
const NOISE = `data:image/svg+xml;utf8,${encodeURIComponent(
  `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180">
     <filter id="n">
       <feTurbulence type="fractalNoise" baseFrequency="0.82" numOctaves="3" stitchTiles="stitch"/>
       <feColorMatrix type="saturate" values="0"/>
     </filter>
     <rect width="180" height="180" filter="url(#n)"/>
   </svg>`,
)}`;

export default function Grain() {
  return (
    <div
      aria-hidden="true"
      className="pointer-events-none fixed inset-0 z-[90] opacity-[0.045] mix-blend-multiply"
      style={{
        backgroundImage: `url("${NOISE}")`,
        backgroundRepeat: 'repeat',
        backgroundSize: '180px 180px',
      }}
    />
  );
}
